name: runTest
on: [push]
jobs:
  test-python-app:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: tmining
          environment-file: env/tmining.yml
      - name: Run runTest
        run: pytest ./tests/run_test.py --cov=./  --cov-report xml:run_testunit.xml
      - name: Run pipeline test
        run: pytest ./tests/pipeline_test.py --cov=./  --cov-report xml:pipelineunit.xml
      - name: Run model test
        run: pytest ./tests/test_model.py --cov=./  --cov-report xml:modelunit.xml
      - name: Run api test
        run: pytest ./tests/api_test.py --cov=./  --cov-report xml:apiunit.xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./pipelineunit.xml, ./modelunit.xml, ./apiunit.xml, ./run_testunit.xml
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Badge Action
        uses: emibcn/badge-action@v2.0.2
